image: bradrydzewski/go:1.3
cache:
  - /go/src/github.com/coreos/go-etcd/etcd
  - /go/src/github.com/couchbaselabs/go-couchbase
  - /go/src/github.com/smartystreets/goconvey
script:
  - go get -u github.com/coreos/go-etcd/etcd
  - go get -u github.com/couchbaselabs/go-couchbase
  - go get -u github.com/smartystreets/goconvey
  - go test
  - go build
notify:
  email:
    recipients:
      - anielkis@gmail.com
