image: bradrydzewski/go:1.3
cache:
  - /go/src/github.com/fjl/go-couchdb
  - /go/src/github.com/deckarep/golang-set
  - /go/src/github.com/coreos/go-etcd
  - /go/src/github.com/smartystreets/goconvey
script:
  - go get -u github.com/deckarep/golang-set
  - go get -u github.com/fjl/go-couchdb
  - go get -u github.com/coreos/go-etcd/etcd
  - go get -u github.com/smartystreets/goconvey
  - go test
  - go build
publish:
  github:
    branch: master
    script:
      - go build
    artifacts:
      - cman
    tag: v$(git branch -q|cut -d ' ' -f 2)-$(git log --pretty=format:'%h' --abbrev-commit HEAD|head -n 1)
    token: {{github_token}}
    user: drone
    repo: drone
notify:
  email:
    recipients:
      - anielkis@gmail.com
